# Generated by Django 2.2.6 on 2019-11-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20191107_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='picture_url',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='picture',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
