# Generated by Django 2.2.6 on 2019-11-11 13:10

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('social', '0003_auto_20191111_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='picture_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follow_user_id',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='request_user_id',
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='picture_user_id',
        ),
        migrations.RemoveField(
            model_name='picturelike',
            name='picture_id',
        ),
        migrations.RemoveField(
            model_name='picturelike',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_id',
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='FollowRequest',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='PictureLike',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
