# Generated by Django 2.2.6 on 2019-11-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20191111_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
