# Generated by Django 2.2.6 on 2019-11-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20191122_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='privacy',
            field=models.BooleanField(default=False, null=True, verbose_name='Privacy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='User Creation Time'),
        ),
    ]
